apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    user: default
    secureJsonData:
      password: edrpassword
    jsonData:
      defaultDatabase: edr
      defaultTable: events
      tlsSkipVerify: true
    editable: true
